// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol KeysGlobalProtocol {
    var allianceApiTokenPublicKey: String { get }
    var allianceApiTokenPassphrase: String { get }
    var glassfyApiKey: String { get }
}

public protocol KeysEnvironmentProtocol {
}
